# cargo

# [[file:~/Workspace/Programming/rust-libs/rust-octree/rust-octree.note::*cargo][cargo:1]]
[package]
name = "octree"
version = "0.0.5"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
timeit = "*"
approx = "*"
# cargo:1 ends here
