# [[file:~/Workspace/Programming/rust-octree/rust-octree.note::1ce15f44-f288-46f0-adcf-a37c35b79dfc][1ce15f44-f288-46f0-adcf-a37c35b79dfc]]
[package]
name = "octree"
version = "0.0.1"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
timeit = "*"
# 1ce15f44-f288-46f0-adcf-a37c35b79dfc ends here
